global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'orderservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5145'] # use service name in compose if in same network
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
